# -*- coding: utf-8 -*-
"""Timetable Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oiqSGUITfXs1cRm39EkHOapamBZ8Enj
"""

import pandas as pd

import random

print ("TIMETABLE GENERATOR\n")
subjects_input=input("Enter subjects (comma seperated):")
days_input=input("Enter days (comma seperated):")
periods_per_day=int(input("Enter periods per day:"))
subjects=[s.strip() for s in subjects_input.split(",") if s.strip()]
days=[d.strip() for d in days_input.split(",") if d.strip()]
if len(subjects)==0 or len(days)==0 or periods_per_day<=0:
  print("Invalid input.please try again.")
else:
  timetable={}
  for day in days:
    timetable[day]=random.choices(subjects,k=periods_per_day)
  # Moved DataFrame creation and display/save outside the loop
  df=pd.DataFrame(timetable)
  df.index=[f"period {i+1}" for i in range(periods_per_day)]
  print("\nTimetable generated successfully\n")
  display(df)
  df.to_csv("Timetable.csv")
  print("\nTimetable saved as timetable.csv")